-- Migration: Add 'wanderer' to tenants plan CHECK constraint
-- Description: The free tier was renamed from 'free' to 'wanderer' in the application,
--   but the DB CHECK constraint was never updated. This caused every free signup to fail
--   with SQLITE_CONSTRAINT_CHECK at step 1 of createTenant().
-- Date: 2026-04-18
--
-- STATUS AS OF 2026-08-19: never applied through this migration file. The
-- rename-and-recreate approach here is unsafe under D1: `PRAGMA foreign_keys
-- = OFF` is a no-op once a transaction is already open, and D1 wraps a
-- migration file's statements in one implicit transaction, so the pragma
-- never took effect. `tenants` has 27 dependent tables holding live foreign
-- keys into it (posts, pages, media, comments, platform_billing, and more) —
-- by far the worst table in the schema to attempt this pattern against.
--
-- Verified against production (2026-08-19): the CHECK constraint already
-- reads `plan IN ('free', 'wanderer', 'seedling', 'sapling', 'oak',
-- 'evergreen')` — someone applied the fix by hand, directly against
-- production, outside the tracked migration history. This file is now a
-- documented no-op so `d1_migrations` can mark it applied and the tracked
-- history matches reality.
--
-- NOTE: a fresh database bootstrapped from migration history alone would
-- still need this fix, since the destructive rebuild above was never
-- proven safe. If that path matters (e.g. local dev seeding from scratch),
-- revisit with a corrected, D1-transaction-safe approach rather than
-- reintroducing the rename-and-recreate pattern against a 27-dependent table.

SELECT 1;
